### ISSUE TITLE
Segmentation doesn't work with saved and reloaded seed image

### ISSUE THREAD

**Issue by ashishsingh18** [dboun/MultiPatientImageProcessing#43]
Segmentation doesn't work with saved and reloaded seed image.

So the steps are:
1. Load some data.
2. Create seed image by using the paint tool.
3. Save the seed image and remove it from application.
4. Reload the seed image -> color coding is lost, 'Run' button is disabled. 
6. Click create seed -> another seed image is created.
7. Click 'Run' -> it fails with a message as in screenshot below

![Capture-segtool](https://user-images.githubusercontent.com/43445206/62146426-5e2ec100-b2c3-11e9-88c0-5334f090c497.PNG)

**Comment by ashishsingh18** [comment]
This is solved by "set as seed'.
@dboun  Can you please confirm?

**Comment by dboun** [comment]
Yep, you should use 'Set as seeds'! (Also 'Convert to segmentation' if you try to load a segmentation and view it).

Please close the issue if you don't have any further questions/suggestions!
