### ISSUE TITLE
Background label color invisible

### ISSUE THREAD

**Issue by ashishsingh18** [dboun/MultiPatientImageProcessing#45]
Background label color is invisible and therefore it is very difficult to erase/modify it.
It needs to be changed to different default color.

**Comment by dboun** [comment]
I picked grey because it's the least intrusive when viewing the final segmentation, but I understand that drawing grey on greyscale images is not ideal. 

We need a color that doesn't pop out. Do you think the color we use for label 5 would be a good choice (dark green I think)?

**Comment by ashishsingh18** [comment]
I would say pick any color, something that is visible. The user can always change it, if needed.

**Comment by dboun** [comment]
Fixed
